### ISSUE TITLE
Logout action gives a 404 page

### ISSUE THREAD

**Issue by Popl7** [ciscospark/spark-js-sdk#223]
When I call the logout action I am redirected to https://idbroker.webex.com/idb/saml2/jsp/doSSO.jsp?type=logout&goto=http%3A%2F%2Flocalhost%3A5555%2F&service=spark

This address gives me a 404 error.

**Comment by ianwremmel** [comment]
hi @Popl7 it has something to do with your the logout url. We're pursuing internally (I think we discussed this a few weeks ago). Will follow up as I know more.

**Comment by pgus** [comment]
Hi @Popl7, when you registered your app you gave a redirect url. You also use this url when you get an auth token. It looks like you used http://localhost which is not routable from the internet. Use a internet routable address and see if that works for you.

**Comment by Popl7** [comment]
The redirect works fine from localhost. 
This is our dev environment. 
On our test env on internet is also doesn't work. 
That is not the problem.

**Comment by ianwremmel** [comment]
I'm told this is fixed. Please reopen if you continue to have issues.

**Comment by Popl7** [comment]
This is still not working for us.
We use:

    function sparkLogout() {
        ciscospark.logout()
                .catch(function(reason) {
                    console.error(reason);
                });
    }

This gives a redirect with an error:

![screen shot 2016-11-16 at 11 36 38](https://cloud.githubusercontent.com/assets/4224518/20344012/3f38f0b2-abf1-11e6-8f8a-acac032f8801.png)

**Comment by Popl7** [comment]
@ianwremmel Can you please re-open the issue?

**Comment by ianwremmel** [comment]
Can you share your app's registered redirect urls as well as the goto url that actually gets used during logout (which you should be able to get by looking at the network tab with "Preserve Log" enabled)?

**Comment by Popl7** [comment]
We build our spark.js with browserify and the following settings:
export CISCOSPARK_CLIENT_ID=MYID
export CISCOSPARK_CLIENT_SECRET=MYSECRET
export CISCOSPARK_SCOPE='spark:messages_write spark:rooms_read spark:teams_read spark:memberships_read spark:messages_read spark:rooms_write spark:people_read spark:team_memberships_write spark:team_memberships_read spark:teams_write spark:memberships_write'
export CISCOSPARK_REDIRECT_URI=http://localhost:5555/

During runtime we use:
    function initSpark() {

        window.spark = ciscospark;
        const l = window.location;

        Object.assign(ciscospark.config.credentials.oauth, {
            redirect_uri: l.protocol + '//' + l.host + l.pathname
        });
       ETC
    }

which sets the redirect_url for the other environments to the correct url.

In my dev tools log I have:

a Post to: https://idbroker.webex.com/idb/oauth2/v1/revoke
a Get to: https://idbroker.webex.com/idb/saml2/jsp/doSSO.jsp?type=logout&goto=http%3A%2F%2Flocalhost%3A5555%2Fassets%2Fspark.html&service=spark

This gives a 302 to: https://idbroker.webex.com/idb/saml2/jsp/saml2error.jsp?errorcode=returnUrlNotAllowed&httpstatuscode=400&errormessage=Retour-URL+is+niet+toegestaan

The http://localhost:5555/assets/spark.html is our spark login on develop.
With our testing server this is a public url but this makes no difference.

**Comment by ianwremmel** [comment]
ok. have you registered "http://localhost:5555/assets/spark.html" on the developer portal or just "http://localhost:5555/"? It needs to be an exact match.

**Comment by Popl7** [comment]
In the developer portal I have registered all urls I use.
For development this is both http://localhost:5555 and http://localhost:5555/assets/spark.html
I have just checked this double and the address is there exactly as the url of the html login page.

**Comment by ianwremmel** [comment]
ok. @pgus, can you do some more digging on the server side to see what's going on?

**Comment by Popl7** [comment]
do you have any more info on this. We'd really like the logout to function properly.
The user experience is horrible now.

**Comment by Popl7** [comment]
@ianwremmel Is someone still working on this?
The redirect means that logging out works really badly.

**Comment by ianwremmel** [comment]
hi @Popl7 We're still working on it. I'm expecting some server updates this week after which I'll need  to make some SDK changes.

**Comment by Popl7** [comment]
This is still an issue for us.

We set the return-url on load and this works fine when logging into Spark.
When we use the spark.logout() method we get a 404 on the Spark webex site.
If I remove the return-url before logging out we don't get the 404 but instead we end up on the webex logged-out-page which is not what should happen.

The expected behaviour is that by clicking logout we might be redirected to Spark to clear the session/cookies/storage but after this we end up on our own page.

Are we doing something wrong or is this something that can be fixed?
